//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.27 at 02:18:52 PM CST 
//


package com.hp.jmx.qc.rest.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Field" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="History" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="List-Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Verify" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="Virtual" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="Editable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="Filterable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="Groupable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="SupportsMultivalue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PhysicalName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "field"
})
@XmlRootElement(name = "Fields")
public class Fields {

    @XmlElement(name = "Field", required = true)
    protected List<Fields.Field> field;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fields.Field }
     * 
     * 
     */
    public List<Fields.Field> getField() {
        if (field == null) {
            field = new ArrayList<Fields.Field>();
        }
        return this.field;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="History" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="List-Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Verify" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Virtual" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Editable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Filterable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Groupable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="SupportsMultivalue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PhysicalName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "size",
        "history",
        "listId",
        "required",
        "system",
        "type",
        "verify",
        "virtual",
        "active",
        "editable",
        "filterable",
        "groupable",
        "supportsMultivalue"
    })
    public static class Field {

        @XmlElement(name = "Size", required = true)
        protected BigInteger size;
        @XmlElement(name = "History")
        protected boolean history;
        @XmlElement(name = "List-Id")
        protected BigInteger listId;
        @XmlElement(name = "Required")
        protected boolean required;
        @XmlElement(name = "System")
        protected boolean system;
        @XmlElement(name = "Type", required = true)
        protected String type;
        @XmlElement(name = "Verify")
        protected boolean verify;
        @XmlElement(name = "Virtual")
        protected boolean virtual;
        @XmlElement(name = "Active")
        protected boolean active;
        @XmlElement(name = "Editable")
        protected boolean editable;
        @XmlElement(name = "Filterable")
        protected boolean filterable;
        @XmlElement(name = "Groupable")
        protected boolean groupable;
        @XmlElement(name = "SupportsMultivalue")
        protected boolean supportsMultivalue;
        @XmlAttribute(name = "Label", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String label;
        @XmlAttribute(name = "Name", required = true)
        protected String name;
        @XmlAttribute(name = "PhysicalName", required = true)
        protected String physicalName;

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSize(BigInteger value) {
            this.size = value;
        }

        /**
         * Gets the value of the history property.
         * 
         */
        public boolean isHistory() {
            return history;
        }

        /**
         * Sets the value of the history property.
         * 
         */
        public void setHistory(boolean value) {
            this.history = value;
        }

        /**
         * Gets the value of the listId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getListId() {
            return listId;
        }

        /**
         * Sets the value of the listId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setListId(BigInteger value) {
            this.listId = value;
        }

        /**
         * Gets the value of the required property.
         * 
         */
        public boolean isRequired() {
            return required;
        }

        /**
         * Sets the value of the required property.
         * 
         */
        public void setRequired(boolean value) {
            this.required = value;
        }

        /**
         * Gets the value of the system property.
         * 
         */
        public boolean isSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         * 
         */
        public void setSystem(boolean value) {
            this.system = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the verify property.
         * 
         */
        public boolean isVerify() {
            return verify;
        }

        /**
         * Sets the value of the verify property.
         * 
         */
        public void setVerify(boolean value) {
            this.verify = value;
        }

        /**
         * Gets the value of the virtual property.
         * 
         */
        public boolean isVirtual() {
            return virtual;
        }

        /**
         * Sets the value of the virtual property.
         * 
         */
        public void setVirtual(boolean value) {
            this.virtual = value;
        }

        /**
         * Gets the value of the active property.
         * 
         */
        public boolean isActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         */
        public void setActive(boolean value) {
            this.active = value;
        }

        /**
         * Gets the value of the editable property.
         * 
         */
        public boolean isEditable() {
            return editable;
        }

        /**
         * Sets the value of the editable property.
         * 
         */
        public void setEditable(boolean value) {
            this.editable = value;
        }

        /**
         * Gets the value of the filterable property.
         * 
         */
        public boolean isFilterable() {
            return filterable;
        }

        /**
         * Sets the value of the filterable property.
         * 
         */
        public void setFilterable(boolean value) {
            this.filterable = value;
        }

        /**
         * Gets the value of the groupable property.
         * 
         */
        public boolean isGroupable() {
            return groupable;
        }

        /**
         * Sets the value of the groupable property.
         * 
         */
        public void setGroupable(boolean value) {
            this.groupable = value;
        }

        /**
         * Gets the value of the supportsMultivalue property.
         * 
         */
        public boolean isSupportsMultivalue() {
            return supportsMultivalue;
        }

        /**
         * Sets the value of the supportsMultivalue property.
         * 
         */
        public void setSupportsMultivalue(boolean value) {
            this.supportsMultivalue = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the physicalName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhysicalName() {
            return physicalName;
        }

        /**
         * Sets the value of the physicalName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhysicalName(String value) {
            this.physicalName = value;
        }

    }

}
